server:
  global:
    ## How frequently to scrape targets by default
    scrape_interval: 15s
    ## How long until a scrape request times out
    scrape_timeout: 10s
    ## How frequently to evaluate rules
    evaluation_interval: 1m