{
 "title": "Alerts",
 "tags": [ "production" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Failed/Pending Pods by User Namespace",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace!~\"(kube-system|tigera-operator|openldap|metallb|longhorn|istio|kubeflow|kyverno|gpu|deploykf|cattle|cert|calico|argocd).*$\"}) by (namespace) + sum(kube_pod_container_status_waiting{namespace!~\"(kube-system|tigera-operator|openldap|metallb|longhorn|istio|kubeflow|kyverno|gpu|deploykf|cattle|cert|calico|argocd).*$\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts Pending Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(alertname) (ALERTS{severity!=\"none\",alertstate!=\"pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}