{
 "title": "K8s TV",
 "description": "The dashboard offers a simple view of the resource consumption of the deployed pods and their impact on the cluster. The outline of requests and limits for each pod and their totals can be used as a tool to determine appropriate resource quotas for your cluster.",
 "tags": [ "production" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "User Namespace CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mCPU" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace!~\"(kube-system|tigera-operator|openldap|metallb|longhorn|istio|kubeflow|kyverno|gpu|deploykf|cattle|cert|calico|argocd).*$\"}[$__rate_interval])) by (namespace)*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Throttle by User Namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_periods_total{namespace!~\"(kube-system|tigera-operator|openldap|metallb|longhorn|istio|kubeflow|kyverno|gpu|deploykf|cattle|cert|calico|argocd).*$\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{namespace!~\"(kube-system|tigera-operator|openldap|metallb|longhorn|istio|kubeflow|kyverno|gpu|deploykf|cattle|cert|calico|argocd).*$\"}) by (namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Circle of Blame",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(namespace) (rate(kube_pod_info{namespace!~\"(kube-system|tigera-operator|openldap|metallb|longhorn|istio|kubeflow|kyverno|gpu|deploykf|cattle|cert|calico|argocd).*$\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=~\"idle|iowait\"}[$__rate_interval]) )by (instance)) + on(instance) group_left(nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - sum(node_memory_MemAvailable_bytes) by (instance) \n/ sum(node_memory_MemTotal_bytes) by (instance)) * 100 + on (instance) group_left(nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Total Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "-avg(rate(node_network_receive_bytes_total[$__rate_interval])) by(instance) + on(instance) group_left(nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    },
    {
     "expr": "avg (rate(node_network_transmit_bytes_total[$__rate_interval])) by (instance) + on(instance) group_left(nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Node GPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL) by (instance,gpu)",
     "legendFormat": "{{instance}};{{gpu}}"
    }
   ]
  },
  {
   "title": "Pods Restarted",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(max by (pod)(increase(kube_pod_container_status_restarts_total[15m]) > 0))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Running Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{}) by (phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "kubelet_running_pod_count{kubernetes_io_role =~ \".*node.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Top 5 Memory Intensive Pods",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5,sum(container_memory_working_set_bytes{image!=\"\"}) by (pod))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory usage per container",
   "type": "table",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_requests{resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "max(container_memory_working_set_bytes{name!=\"\"}) by (pod)/max(kube_pod_container_resource_limits{resource=\"memory\"}) by (pod) *100"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container_name!=\"POD\"}[$__rate_interval])) by (pod)/max(kube_pod_container_resource_limits{resource=\"cpu\"}) by (pod) * 100"
    },
    {
     "expr": "max(kube_pod_info) by (pod,namespace,node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPUs per Namespace Quota",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{type=\"used\", resource=\"cpu\"}) by (namespace,resource) / sum(kube_resourcequota{type=\"hard\",resource=\"cpu\"}) by (namespace,resource)   * 100",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "GPUs per Namespace Quota",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{type=\"used\", resource!~\"cpu|persistentvolumeclaims|memory\"}) by (namespace,resource) / sum(kube_resourcequota{type=\"hard\",resource!~\"cpu|persistentvolumeclaims|memory\"}) by (namespace,resource)   * 100",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory per Namespace Quota",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{type=\"used\", resource=\"memory\"}) by (namespace,resource) / sum(kube_resourcequota{type=\"hard\",resource=\"memory\"}) by (namespace,resource)   * 100",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Persistentvolumes per Namespace Quota",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{type=\"used\", resource=\"persistentvolumeclaims\"}) by (namespace) / sum(kube_resourcequota{type=\"hard\",resource=\"persistentvolumeclaims\"}) by (namespace)   * 100",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}